title: SB Software Docs
description: The place to be for IPOS documentation!
theme: just-the-docs

url: https://sb-docs.github.io

aux_links:
  SB Software page: https://sbsoftretail.com
  Facebook: https://www.facebook.com/SBSoftwareSolutiiRetail
