title: SB Software Docs
description: The place to be for IPOS documentation!
theme: just-the-docs

url: https://bbcwiki.github.io/JustTheDocs2

aux_links:
  SB Software page: https://sbsoftretail.com
  Facebook: https://www.facebook.com/SBSoftwareSolutiiRetail

color_scheme: dark
